device: cuda
dry_run: false
seed: 42

chdir: "."
model: EleutherAI/pythia-2.8b

dataset: stas/c4-en-10k
use_log2_entropy: false
data_range_start: 0
data_range_end: 1000
batch_size: 1
k: 10
neuron_range: null
hf_token_path: ./hf_token.txt

output_dir: results
transformers_cache_dir: null


defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .